ces:
  - docker

before_script:
  - cd simplequeue && make clean

script:
  - make unit-test integration-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make clean

cache:
  directories:
  - $HOME/.m2
