version: "3"

services:
  redis:
    image: "redis:4"
    command: sh -c "sleep 8 && redis-server"

  waiter:
    image: "jwilder/dockerize"
    command: "true"

  test-runner:
    image: "maven:3.5-jdk-8-alpine"
    volumes:
      - "$PWD/m2/:/root/.m2"
      - "$PWD:/project"
    working_dir: "/project"
    command: "true"


  
