name: Test
on: [push]
defaults:
  run:
    working-directory: simplequeue
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Cleanup workspace
        run: make clean
      - name: Unit tests
        run: make unit-test
      - name: Integration tests
        run: make integration-test

