version: '3'

services:
  frontend:
    build: .
    command: ng serve --host 0.0.0.0
    ports:
    - "4200:4200"
  # Mock backend
  backend:
    image: clue/json-server
    volumes:
      - "./db.json:/data/db.json"


