version: '3'

services: 
  app:
    build: .
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: toor
      MYSQL_DATABASE_DB: todos
      MYSQL_DATABASE_HOST: database
    ports:
      - "5000:5000"
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
