version: '2.1'

services:
  redis:
    image: redis:4-alpine
  waiter:
    image: jwilder/dockerize
    command: "true"
  test-runner:
    image: maven:3.5-jdk-8-alpine
    command: "true"
    volumes:
      - ./.m2:/root/.m2
      - .:/src

